/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4628e45c-7b1d-48f4-812f-823d3618c1a4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_vK3fx2kqh",
    "aws_user_pools_web_client_id": "1rdug5im5tgmjvvg8c5r0ef1c2",
    "oauth": {}
};


export default awsmobile;
